services:

  ejemplopresta.module:
    class: ejemplopresta
    public: true
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'ejemplopresta'

  ejemplopresta.context:
    class: Context
    public: true
    factory: [ 'Context', 'getContext' ]
    
  #####################
  # PS Account
  ejemplopresta.ps_accounts_installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    public: true
    arguments:
      - "5.0"

  ejemplopresta.ps_accounts_facade:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    public: true
    arguments:
      - "@ejemplopresta.ps_accounts_installer"

  #####################
  # PS Billing
  ejemplopresta.ps_billings_context_wrapper:
    class: 'PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
    arguments:
      - '@ejemplopresta.ps_accounts_facade'
      - '@ejemplopresta.context'
      - true # if true you are in sandbox mode, if false or empty not in sandbox

  ejemplopresta.ps_billings_facade:
    class: 'PrestaShopCorp\Billing\Presenter\BillingPresenter'
    public: true
    arguments:
      - '@ejemplopresta.ps_billings_context_wrapper'
      - '@ejemplopresta.module'

  # Remove this if you don't need BillingService
  ejemplopresta.ps_billings_service:
    class: PrestaShopCorp\Billing\Services\BillingService
    public: true
    arguments:
      - '@ejemplopresta.ps_billings_context_wrapper'
      - '@ejemplopresta.module'